# Generated by Django 3.2.25 on 2025-10-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listing',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Rented', 'Rented'), ('Expired', 'Expired')], default='Active', max_length=64),
        ),
    ]
