# Generated by Django 5.2.7 on 2025-11-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_rental_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Stationery', 'Stationery'), ('Books', 'Books'), ('Others', 'Others')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rental_listing',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('Active', 'Active'), ('Rented', 'Rented'), ('Expired', 'Expired')], default='processing', max_length=10),
        ),
    ]
