# Generated by Django 4.2.1 on 2023-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Books", "Books"),
                    ("Electronics", "Electronics"),
                    ("Stationery", "Stationery"),
                    ("Others", "Others"),
                ],
                max_length=64,
            ),
        ),
    ]
