# Generated by Django 4.2.1 on 2023-06-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mart", "0002_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="contact",
            field=models.BigIntegerField(default=9999999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Accessories", "Accessories"),
                    ("Electronics", "Electronics"),
                    ("Stationery", "Stationery"),
                    ("Others", "Others"),
                ],
                max_length=64,
            ),
        ),
    ]
