# Generated by Django 5.2.7 on 2025-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_listing_contact_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Stationery', 'Stationery'), ('Books', 'Books'), ('Others', 'Others')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired')], default='processing', max_length=10),
        ),
    ]
